/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Connect.Connect;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
//import java.awt.Dimension;
//import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.lang.System.Logger;
//import java.lang.System.Logger.Level;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JTable;
//import java.util.logging.Logger;

/**
 *
 * @author ThinkPad X1 Carbon
 */
public class dataPemesanTiket extends javax.swing.JFrame {

    DefaultTableModel model;

    public dataPemesanTiket() {
        initComponents();
        Object[] header = {"Nomor", "Nama", "Nomor_Kursi", "Jumlah_Tiket", "Total_Bayar", "Uang_Bayar", "Uang_Kembalian", "ShowCase", "Harga"};
        model = new DefaultTableModel(header, 0);
        tableData.setModel(model);
        tableData.getColumnModel().getColumn(0).setMinWidth(35);
        tableData.getColumnModel().getColumn(0).setMaxWidth(35);
        tableData.getColumnModel().getColumn(1).setMinWidth(150);
        tableData.getColumnModel().getColumn(1).setMaxWidth(150);
        tableData.getColumnModel().getColumn(2).setMinWidth(150);
        tableData.getColumnModel().getColumn(2).setMaxWidth(150);
        tableData.getColumnModel().getColumn(3).setMinWidth(150);
        tableData.getColumnModel().getColumn(3).setMaxWidth(150);
        tableData.getColumnModel().getColumn(4).setMinWidth(150);
        tableData.getColumnModel().getColumn(4).setMaxWidth(150);
        tableData.getColumnModel().getColumn(5).setMinWidth(150);
        tableData.getColumnModel().getColumn(5).setMaxWidth(150);
        tableData.getColumnModel().getColumn(6).setMinWidth(150);
        tableData.getColumnModel().getColumn(6).setMaxWidth(150);
        tableData.getColumnModel().getColumn(7).setMinWidth(150);
        tableData.getColumnModel().getColumn(7).setMaxWidth(150);

        loadData();

        setTitle("Data Tiket Konser");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jns = new javax.swing.JComboBox<>();
        harga = new javax.swing.JLabel();
        hrgField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        FieldName = new javax.swing.JTextField();
        jmlTiket = new javax.swing.JTextField();
        nmrKursi = new javax.swing.JTextField();
        ttlBayar = new javax.swing.JTextField();
        uangByr = new javax.swing.JTextField();
        uangKmblian = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        btnSmpn = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnGenerate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jenis");

        jns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SHOWCASE", "REGULER", "PREMIUM", "VIP" }));
        jns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnsActionPerformed(evt);
            }
        });

        harga.setForeground(new java.awt.Color(255, 255, 255));
        harga.setText("Harga");

        hrgField.setBackground(new java.awt.Color(102, 102, 102));
        hrgField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrgFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jns, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hrgField))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(harga)
                    .addComponent(hrgField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nama");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jumlah Tiket");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nomor Kursi");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total Bayar");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Uang Bayar");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Uang Kembalian");

        FieldName.setBackground(new java.awt.Color(102, 102, 102));
        FieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNameActionPerformed(evt);
            }
        });

        jmlTiket.setBackground(new java.awt.Color(102, 102, 102));
        jmlTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlTiketActionPerformed(evt);
            }
        });
        jmlTiket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jmlTiketKeyReleased(evt);
            }
        });

        nmrKursi.setBackground(new java.awt.Color(102, 102, 102));
        nmrKursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmrKursiActionPerformed(evt);
            }
        });

        ttlBayar.setBackground(new java.awt.Color(102, 102, 102));
        ttlBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttlBayarActionPerformed(evt);
            }
        });

        uangByr.setBackground(new java.awt.Color(102, 102, 102));
        uangByr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangByrActionPerformed(evt);
            }
        });
        uangByr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uangByrKeyReleased(evt);
            }
        });

        uangKmblian.setBackground(new java.awt.Color(102, 102, 102));
        uangKmblian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangKmblianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9))
                .addGap(81, 81, 81)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jmlTiket)
                    .addComponent(nmrKursi)
                    .addComponent(ttlBayar)
                    .addComponent(uangByr)
                    .addComponent(uangKmblian, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(FieldName))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(FieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jmlTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nmrKursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(19, 19, 19)
                                .addComponent(ttlBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12))
                        .addGap(19, 19, 19)
                        .addComponent(uangByr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uangKmblian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        tableData.setBackground(new java.awt.Color(153, 153, 153));
        tableData.setForeground(new java.awt.Color(255, 255, 255));
        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nomor", "Nama", "Harga", "Jumlah Tiket", "Nomor Kursi", "Total Bayar", "Uang Bayar", "Uang Kembalian"
            }
        ));
        tableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableDataMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableData);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 1058, 101));

        btnSmpn.setBackground(new java.awt.Color(102, 102, 102));
        btnSmpn.setForeground(new java.awt.Color(0, 0, 0));
        btnSmpn.setText("Simpan");
        btnSmpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnActionPerformed(evt);
            }
        });
        jPanel2.add(btnSmpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, -1, -1));

        btnEdit.setBackground(new java.awt.Color(102, 102, 102));
        btnEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel2.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, 70, -1));

        btnKeluar.setBackground(new java.awt.Color(102, 102, 102));
        btnKeluar.setForeground(new java.awt.Color(0, 0, 0));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel2.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, -1, -1));

        btnHapus.setBackground(new java.awt.Color(102, 102, 102));
        btnHapus.setForeground(new java.awt.Color(0, 0, 0));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 610, 70, -1));

        btnGenerate.setBackground(new java.awt.Color(102, 102, 102));
        btnGenerate.setForeground(new java.awt.Color(0, 0, 0));
        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        jPanel2.add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 610, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dark-grunge-style-scratched-metal-surface.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hrgFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrgFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrgFieldActionPerformed

    private void FieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNameActionPerformed

    private void nmrKursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmrKursiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmrKursiActionPerformed

    private void uangByrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangByrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uangByrActionPerformed

    private void uangKmblianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangKmblianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uangKmblianActionPerformed

    private void btnSmpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO tiket (Showcase, Harga, Nama, Jumlah_Tiket, Nomor_Kursi, Total_Bayar, Uang_Bayar, Uang_Kembalian) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

            Connection conn = Connect.MySQL();
            com.mysql.cj.jdbc.ClientPreparedStatement pstm = (com.mysql.cj.jdbc.ClientPreparedStatement) conn.prepareStatement(sql);

            pstm.setString(1, String.valueOf(jns.getSelectedItem()));
            pstm.setString(2, hrgField.getText());
            pstm.setString(3, FieldName.getText());
            pstm.setString(4, jmlTiket.getText());
            pstm.setString(5, nmrKursi.getText());
            pstm.setString(6, ttlBayar.getText());
            pstm.setString(7, uangByr.getText());
            pstm.setString(8, uangKmblian.getText());

            pstm.executeUpdate();

            JOptionPane.showMessageDialog(null, "Proses Simpan Berhasil");
            loadData();
            clearInputFields();

//    KosongkanForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_btnSmpnActionPerformed

    private void jnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnsActionPerformed

        if (jns.getSelectedItem().equals("REGULER")) {
            hrgField.setText("50000");
        } else if (jns.getSelectedItem().equals("PREMIUM")) {
            hrgField.setText("100000");
        } else if (jns.getSelectedItem().equals("VIP")) {
            hrgField.setText("250000");
        }
    }//GEN-LAST:event_jnsActionPerformed

    private void jmlTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlTiketActionPerformed

    private void jmlTiketKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmlTiketKeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a = Integer.valueOf(hrgField.getText());
        b = Integer.valueOf(jmlTiket.getText());
        c = a * b;
        ttlBayar.setText("" + c);
        String value = jmlTiket.getText();
        if (!value.isEmpty()) {
            int intValue = Integer.parseInt(value);
        } else {
            JOptionPane.showMessageDialog(null, "Input tidak boleh kosong!");
        }
    }//GEN-LAST:event_jmlTiketKeyReleased

    private void ttlBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttlBayarActionPerformed
        // TODO add your handling code here:
        int a, b, c;
        a = Integer.valueOf(hrgField.getText());
        b = Integer.valueOf(jmlTiket.getText());
        c = a * b;
        ttlBayar.setText("" + c);
    }//GEN-LAST:event_ttlBayarActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here: 
        int selectedRowIndex = tableData.getSelectedRow();
        String selectedId = tableData.getValueAt(selectedRowIndex, 0).toString();
        try {
            String sql = "UPDATE tiket SET Showcase = ?, Harga = ?, Nama = ?, Jumlah_Tiket = ?, Nomor_Kursi = ?, Total_Bayar = ?, Uang_Bayar = ?, Uang_Kembalian = ? WHERE id = ?";
            java.sql.Connection conn;
            conn = (Connection) Connect.MySQL();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);

            pstm.setString(1, jns.getSelectedItem().toString());
            pstm.setString(2, hrgField.getText());
            pstm.setString(3, FieldName.getText());
            pstm.setString(4, jmlTiket.getText());
            pstm.setString(5, nmrKursi.getText());
            pstm.setString(6, ttlBayar.getText());
            pstm.setString(7, uangByr.getText());
            pstm.setString(8, uangKmblian.getText());
            pstm.setString(9, selectedId);

            pstm.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            loadData();
            clearInputFields();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:        
        int r = tableData.getSelectedRow();
        if (r != -1) {
            int kode = Integer.parseInt(tableData.getValueAt(r, 0).toString());
            int pilih = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (pilih == 0) {
                try {
                    Connection c = Connect.MySQL();
                    Statement st = c.createStatement();
                    String q = "DELETE FROM tiket WHERE id=" + kode + "";
                    st.executeUpdate(q);
                    loadData();
                    clearInputFields(); 
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus ");
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
        } else {
            // Tidak ada baris yang dipilih
        }


    }//GEN-LAST:event_btnHapusActionPerformed

    private void uangByrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uangByrKeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a = Integer.valueOf(uangByr.getText());
        b = Integer.valueOf(ttlBayar.getText());
        c = a - b;
        uangKmblian.setText("" + c);
    }//GEN-LAST:event_uangByrKeyReleased

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        int row = tableData.getRowCount();
        for (int i = 0; i < row; i++) {
            String nama = tableData.getValueAt(i, 1).toString();
            String data = nama;
            String path = nama + ".png";
            String charset = "UTF-8";
            Map<EncodeHintType, ErrorCorrectionLevel> hashMap = new HashMap<>();

            hashMap.put(EncodeHintType.ERROR_CORRECTION,
                    ErrorCorrectionLevel.L);

            try {
                BitMatrix matrix = new MultiFormatWriter().encode(
                        new String(data.getBytes(charset), charset),
                        BarcodeFormat.QR_CODE, 200, 200);

                File f = new File("QR");

                if (!f.exists()) {
                    f.mkdir();
                }

                MatrixToImageWriter.writeToFile(
                        matrix,
                        path.substring(path.lastIndexOf('.') + 1),
                        new File("QR/" + path));
            } catch (WriterException | IOException e) {
            }

        }
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void tableDataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tableDataMouseReleased

    private void tableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseClicked
        // TODO add your handling code here:
        int row = tableData.getSelectedRow();
        String Nama = tableData.getValueAt(row, 1).toString();
        String NomorKursi = tableData.getValueAt(row, 2).toString();
        String JumlahTiket = tableData.getValueAt(row, 3).toString();
        String TotalBayar = tableData.getValueAt(row, 4).toString();
        String UangBayar = tableData.getValueAt(row, 5).toString();
        String Harga = tableData.getValueAt(row, 8).toString();
        String jnis = tableData.getValueAt(row, 7).toString();
        String UangKembalian = tableData.getValueAt(row, 6).toString();

        jns.setSelectedItem(jnis);
        FieldName.setText(Nama);
        hrgField.setText(Harga);
        jmlTiket.setText(JumlahTiket);
        nmrKursi.setText(NomorKursi);
        ttlBayar.setText(TotalBayar);
        uangByr.setText(UangBayar);
        uangKmblian.setText(UangKembalian);
    }//GEN-LAST:event_tableDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataPemesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataPemesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataPemesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataPemesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataPemesanTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FieldName;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSmpn;
    private javax.swing.JLabel harga;
    private javax.swing.JTextField hrgField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jmlTiket;
    private javax.swing.JComboBox<String> jns;
    private javax.swing.JTextField nmrKursi;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField ttlBayar;
    private javax.swing.JTextField uangByr;
    private javax.swing.JTextField uangKmblian;
    // End of variables declaration//GEN-END:variables

    public void loadData() {
        try {
            model.setRowCount(0);
            Connection c = Connect.MySQL();
            Statement st = c.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM tiket");
            int no = 0;

            while (rs.next()) {
                no++;
                String data_nama = rs.getString("Nama");
                String data_Kursi = rs.getString("Nomor_Kursi");
                String data_Tiket = rs.getString("Jumlah_Tiket");
                String data_Bayar = rs.getString("Total_Bayar");
                String data_Uang = rs.getString("Uang_Bayar");
                String data_Kembalian = rs.getString("Uang_Kembalian");
                String data_ShowCase = rs.getString("ShowCase");
                String data_Harga = rs.getString("Harga");

//                System.out.println(data_city);
                Object[] data = {no, data_nama, data_Kursi, data_Tiket, data_Bayar, data_Uang, data_Kembalian, data_ShowCase, data_Harga};
                int jumlah = data.length - 1;
                model.addRow(data);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void clearInputFields() {
        jns.setSelectedItem("");
        hrgField.setText("");
        FieldName.setText("");
        jmlTiket.setText("");
        nmrKursi.setText("");
        ttlBayar.setText("");
        uangByr.setText("");
        uangKmblian.setText("");

    }

}
